name: Build and Update Helm Chart

on:
push:
tags:
- 'dev-v*'

jobs:
build-and-push:
runs-on: ubuntu-latest

steps:
  - name: Checkout code
    uses: actions/checkout@v3

  - name: Set up Docker
    uses: docker/setup-buildx-action@v2

  - name: Authenticate to Google Cloud
    uses: google-github-actions/auth@v1
    with:
      credentials_json: ${{ secrets.GCP_SA_KEY }}

  - name: Configure Docker for Artifact Registry
    run: gcloud auth configure-docker REGION-docker.pkg.dev

  - name: Build Docker image
    run: |
      IMAGE_NAME=my-nginx-app
      TAG=${GITHUB_REF#refs/tags/}
      FULL_IMAGE=REGION-docker.pkg.dev/PROJECT_ID/my-docker-repo/$IMAGE_NAME:$TAG
      docker build -t $FULL_IMAGE .
      docker push $FULL_IMAGE

  - name: Update Helm chart values.yaml
    uses: stefanzweifel/git-auto-commit-action@v4
    with:
      commit_message: "Update image tag to ${{ github.ref_name }}"
      file_pattern: "values.yaml"
      branch: "main"
    env:
      IMAGE_TAG: ${{ github.ref_name }}
