name: Build and Update Helm Chart

on:
  push:
    tags:
      - 'dev-v*'

jobs:
  build-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout app repo
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=my-app
          TAG=${GITHUB_REF#refs/tags/}
          FULL_IMAGE=us-central1-docker.pkg.dev/rock-figure-384119/my-docker-repo/$IMAGE_NAME:$TAG
          echo "Full image: $FULL_IMAGE"
          docker build -t $FULL_IMAGE .
          docker push $FULL_IMAGE

      - name: Checkout Helm charts repo
        uses: actions/checkout@v3
        with:
          repository: your-org/my-charts-repo
          token: ${{ secrets.GITHUB_TOKEN }}
          path: my-charts

      - name: Update Helm chart values.yaml
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          sed -i "s|tag: .*|tag: $TAG|" my-charts/values.yaml

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update image tag to ${{ github.ref_name }}"
          branch: main
          file_pattern: "my-charts/values.yaml"
